Exercises
shaypheraddison/shayshay-javascript pull request #4
Opened 2024-03-29 21:14 UTC by shaypheraddison

2024-03-31 23:06 UTC, resoluteCoder requested changes

2024-03-31 23:06 UTC, resoluteCoder commented on exercises/exercise1.js
> +const totalSum = receipt.apples + receipt.milk + receipt.appleJuice + receipt.cups + receipt.dogFood;
Can you find a better way to add the sum?

2024-03-31 23:06 UTC, resoluteCoder commented on exercises/exercise1.js
> +    console.log(item);
Try string interpolation

2024-03-31 23:06 UTC, resoluteCoder commented on exercises/exercise2.js
> +        console.log(face + " of " + suit);
This prints them out not creating a deck of cards with string values

2024-03-31 23:06 UTC, resoluteCoder commented on exercises/exercise3.js
> +}
This needs to a deck of cards where each card is an object. You are printing them.

2024-03-31 23:06 UTC, resoluteCoder commented on exercises/exercise4.js
> +    console.log(star);
Negative ghost rider 😄

2024-04-01 19:37 UTC, shaypheraddison commented on exercises/exercise2.js
> +        console.log(face + " of " + suit);
completed this and have pushed the commit

2024-04-01 19:38 UTC, shaypheraddison commented on exercises/exercise1.js
> +    console.log(item);
added string interpolation and pushed commit

2024-04-01 20:28 UTC, shaypheraddison commented on exercises/exercise3.js
> +}
Corrected to have each card as an object. pushed commit as well

2024-04-02 00:26 UTC, shaypheraddison commented on exercises/exercise1.js
> +const totalSum = receipt.apples + receipt.milk + receipt.appleJuice + receipt.cups + receipt.dogFood;
Added a more efficient way to calculate sum in new commit.

2024-04-02 20:08 UTC, resoluteCoder requested changes

2024-04-02 20:08 UTC, resoluteCoder commented on exercises/exercise3.js
> +        newDeck = {Face: face, Suit: suit};
Take a close look at this line. How many `newDeck` will be created.  Will `newDeck` have all the cards in it?

2024-04-02 20:10 UTC, shaypheraddison commented on exercises/exercise4.js
> +    console.log(star);
This has been properly completed. Forgot to respond to this.

2024-04-03 16:49 UTC, resoluteCoder approved these changes

2024-04-03 16:49 UTC, resoluteCoder commented on exercises/exercise3.js
> +var newDeck = [];
Why var?

2024-04-03 16:49 UTC, resoluteCoder commented on exercises/exercise3.js
> +} console.log(newDeck);
log on new line? 😄

2024-04-03 16:49 UTC, resoluteCoder commented
Looks good just left a couple of comments but it can be merged that way. Good job!

2024-04-03 16:57 UTC, merged